CREATE TABLE IF NOT EXISTS speed_tests (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  test_uuid CHAR(36) NOT NULL UNIQUE,
  download_mbps DECIMAL(10,2) NOT NULL,
  upload_mbps DECIMAL(10,2) NOT NULL,
  ping_ms DECIMAL(10,2) NOT NULL,
  jitter_ms DECIMAL(10,2) NOT NULL,
  packet_loss_pct DECIMAL(6,2) NOT NULL DEFAULT 0,
  score TINYINT UNSIGNED NOT NULL,
  server_id VARCHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_speed_tests_created_at (created_at),
  INDEX idx_speed_tests_server (server_id)
);

CREATE TABLE IF NOT EXISTS test_servers (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  region VARCHAR(80) NOT NULL,
  endpoint_url VARCHAR(255) NOT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS service_events (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  event_type VARCHAR(64) NOT NULL,
  severity VARCHAR(16) NOT NULL DEFAULT 'info',
  message VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_events_created_at (created_at)
);
